name: manage-azure-policy-54e29c60
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Application_Insights_components_should_block_non-Azure_Active_Directory_based_ingestion._199d5677-e4d9-4264-9465-efe1839c06bd/**'
#      - 'policies/Application_Insights_components_should_block_log_ingestion_and_querying_from_public_networks_1bc02227-0cb6-4e11-8f53-eb0b22eab7e8/**'
#      - 'policies/Azure_Monitor_Logs_for_Application_Insights_should_be_linked_to_a_Log_Analytics_workspace_d550e854-df1a-4de9-bf44-cd894b39a95e/**'
#      - 'policies/Configure_Azure_Application_Insights_components_to_disable_public_network_access_for_log_ingestion_and_querying_dddfa1af-dcd6-42f4-b5b0-e1db01e0b405/**'
#      - 'policies/Azure_SQL_Database_should_be_running_TLS_version_1.2_or_newer_32e6bbec-16b6-44c2-be37-c5b672d103cf/**'
#      - 'policies/Function_apps_should_only_be_accessible_over_HTTPS_6d555dd1-86f2-4f1c-8ed7-5abae7c6cbab/**'
#      - 'policies/App_Service_apps_should_only_be_accessible_over_HTTPS_a4af4a39-4135-47fb-b175-47fbdf85311d/**'
#      - .github/workflows/manage-azure-policy-54e29c60.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_54e29c60}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Application_Insights_components_should_block_non-Azure_Active_Directory_based_ingestion._199d5677-e4d9-4264-9465-efe1839c06bd/**
          policies/Application_Insights_components_should_block_log_ingestion_and_querying_from_public_networks_1bc02227-0cb6-4e11-8f53-eb0b22eab7e8/**
          policies/Azure_Monitor_Logs_for_Application_Insights_should_be_linked_to_a_Log_Analytics_workspace_d550e854-df1a-4de9-bf44-cd894b39a95e/**
          policies/Configure_Azure_Application_Insights_components_to_disable_public_network_access_for_log_ingestion_and_querying_dddfa1af-dcd6-42f4-b5b0-e1db01e0b405/**
          policies/Azure_SQL_Database_should_be_running_TLS_version_1.2_or_newer_32e6bbec-16b6-44c2-be37-c5b672d103cf/**
          policies/Function_apps_should_only_be_accessible_over_HTTPS_6d555dd1-86f2-4f1c-8ed7-5abae7c6cbab/**
          policies/App_Service_apps_should_only_be_accessible_over_HTTPS_a4af4a39-4135-47fb-b175-47fbdf85311d/**
